"""
Command execution layer for JARVIS.

This module takes a parsed command and executes the corresponding action.
"""

from datetime import datetime
from zoneinfo import ZoneInfo

from core.calculator import calculate
from core.commands import Command, CommandType
from core.math_normalizer import normalize_math_expression


class CommandExecutor:
    """
    Executes commands produced by the command parser.
    """

    def execute(
            self,
            command: Command,
        ) -> str:
        """
        Execute a parsed command.

        Args:
            command:
                Parsed command produced by CommandParser.

        Returns:
            Response generated by JARVIS.
        """

        if command.command_type is CommandType.GREETING:
            return "HELLO, SIR! How can I help you?"

        if command.command_type is CommandType.GET_TIME:
            return self._get_time()

        if command.command_type is CommandType.CALCULATE:
            return self._calculate(command.text)

        if command.command_type is CommandType.EXIT:
            return "Goodbye, Sir."

        return "Sorry, I don't understand that command."

    @staticmethod
    def _get_time() -> str:
        """
        Return the current local time.
        """

        current_time = datetime.now(
            ZoneInfo("Asia/Kolkata")
            ).strftime("%I:%M %p")

        return f"The current time is {current_time}."

    @staticmethod
    def _calculate(text: str) -> str:
        """
        Execute a basic arithmetic calculation using normalize_math_expression and calculate.
        """
        if not text or not text.strip():
            return "I could not find a calculation to perform."

        cleaned = text.strip().lower()

        # Check for explicit no-expression calculation requests
        if cleaned in {
            "calculate",
            "compute",
            "solve",
            "calculate nothing",
        }:
            return "I could not find a calculation to perform."

        try:
            normalized_expr = normalize_math_expression(text)
            result = calculate(normalized_expr)

        except ZeroDivisionError:
            return "I cannot divide by zero."

        except ValueError:
            return "I could not understand that calculation."

        return f"The answer is {result}."
